services:
  db:
    image: postgres:15
    container_name: gatchalife-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gatchalife -d gatchalife"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - proxy-network
      - postgres-network

  backend:
    build:
      context: ./GatchaLife-backend
      target: dev
    container_name: gatchalife-backend
    volumes:
      - ./GatchaLife-backend:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/static/images
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - proxy-network
      - postgres-network

  frontend:
    build:
      context: ./GatchaLife-frontend
      target: dev
    container_name: gatchalife-frontend
    volumes:
      - ./GatchaLife-frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - proxy-network
      - postgres-network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  proxy-network:
  postgres-network:
