services:
  backend:
    build: 
      context: .
      dockerfile: ./GatchaLife-backend/Dockerfile
    container_name: gatchalife-backend
    restart: unless-stopped
    networks:
      - proxy-network
      - postgres-network
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=gatchalife
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=gatcha.tlafay.fr,localhost,127.0.0.1
      - N8N_BASE_URL=${N8N_BASE_URL}
      - N8N_WORKFLOW_WEBHOOK_PATH=${N8N_WORKFLOW_WEBHOOK_PATH}
      - N8N_GENERATE_IMAGE_WORKFLOW_ID=${N8N_GENERATE_IMAGE_WORKFLOW_ID}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/static/images

  frontend:
    build:
      context: .
      dockerfile: ./GatchaLife-frontend/Dockerfile
    container_name: gatchalife-frontend
    restart: unless-stopped
    networks:
      - proxy-network
    environment:
      - VITE_API_BASE_URL=https://gatcha.tlafay.fr/api
    depends_on:
      - backend

networks:
  proxy-network:
    external: true
  postgres-network:
    external: true

volumes:
  static_volume:
  media_volume:
