services:
  backend:
    build:
      context: ./GatchaLife-backend
      dockerfile: Dockerfile
    container_name: gatchalife-backend
    restart: unless-stopped
    networks:
      - proxy-network
      - gatchalife-network
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=gatchalife
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=gatcha.tlafay.fr,gatchalife-backend,localhost,127.0.0.1
      - N8N_BASE_URL=${N8N_BASE_URL}
      - N8N_WORKFLOW_WEBHOOK_PATH=${N8N_WORKFLOW_WEBHOOK_PATH}
      - N8N_GENERATE_IMAGE_WORKFLOW_ID=${N8N_GENERATE_IMAGE_WORKFLOW_ID}
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/static/images

  redis:
    image: redis:7-alpine
    container_name: gatchalife-redis
    restart: unless-stopped
    networks:
      - gatchalife-network
    volumes:
      - redis_data:/data


  frontend:
    build:
      context: ./GatchaLife-frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=https://gatcha.tlafay.fr/api
    container_name: gatchalife-frontend
    restart: unless-stopped
    networks:
      - proxy-network
    environment:
      - VITE_API_BASE_URL=https://gatcha.tlafay.fr/api
    depends_on:
      - backend
    volumes:
      - media_volume:/usr/share/nginx/media

  celery:
    build:
      context: ./GatchaLife-backend
      dockerfile: Dockerfile
    container_name: gatchalife-celery
    command: celery -A gatchalife worker --loglevel=info
    restart: unless-stopped
    networks:
      - gatchalife-network
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=gatchalife
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - backend

  celery-beat:
    build:
      context: ./GatchaLife-backend
      dockerfile: Dockerfile
    container_name: gatchalife-celery-beat
    command: celery -A gatchalife beat --loglevel=info
    restart: unless-stopped
    networks:
      - gatchalife-network
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=gatchalife
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
      - backend

networks:
  proxy-network:
    external: true
    name: services_proxy-network  # <--- ADD THIS LINE mapping
  gatchalife-network:
    external: true
    name: services_gatchalife        # <--- ADD THIS (See explanation below)

volumes:
  static_volume:
  media_volume:
  redis_data:
